baseURL = "https://turgeonmaxime.github.io/w20-stat7200/"
languageCode = "en-us"
title = "STAT 7200 - Winter 2020"
theme = "book"
ignoreFiles = ["_files$", "_cache$"]

[params]
BookMenuBundle = "/menu"
BookToC = false
BookSearch = false
